### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by keozx** [NAXAM/braintree-android-binding#1]
Hello, I have integrated your binding but I get this error in Android on build:

obj\Debug\android\src\mono\com\braintreepayments\api\interfaces\TokenizationParametersListenerImplementor.java(4,8): error :  error: TokenizationParametersListenerImplementor is not abstract and does not override abstract method onResult(PaymentMethodTokenizationParameters,Collection<Integer>) in TokenizationParametersListener

Thanks

**Comment by keozx** [comment]
Solved it, you must add an Additions file with this code

```
   internal sealed partial class ITokenizationParametersListenerImplementor
    {
        public void onResult(PaymentMethodTokenizationParameters p0, Java.Util.ICollection p1)
        {

        }
    }
```

This requires adding google wallet nuget

**Comment by tuyen-vuduc** [comment]
:). That code isn't complete. It just made you build ok.

**Comment by utkarsh-rathor** [comment]
I'm getting this same error while trying to bind new libraries, any idea as to why this is happening, should i override it in the metadata?
