### ISSUE TITLE
Venmo not showing up in Drop In UI

### ISSUE THREAD

**Issue by jmbowman1107** [NAXAM/braintree-android-binding#13]
I have been trying to get Venmo to show up with the drop-in on Android with no luck. 

I noticed in the Braintree SDK docs this:

  // to offer Venmo
  implementation 'com.braintreepayments.api:venmo:4.+'

Is this API part of the binding?

**Comment by tuyen-vuduc** [comment]
Please check out the latest version and reopen in case
