### ISSUE TITLE
com.braintreepayments.api.internal.AnalyticsIntentService  cannot be instantiated 

### ISSUE THREAD

**Issue by samirgcofficial** [NAXAM/braintree-android-binding#15]
On Debug Mode I am able to complete the payment with my token from the Server where as on release mode this is the Log : 
Platform Used :  Xamarin Forms  -> Android 

[System.out] [okhttp]:check permission begin!
[System] ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
[System.out] [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
[System.out] [OkHttp] sendRequest>>
[System.out] [OkHttp] sendRequest<<
[com.pastryworld] type=1400 audit(0.0:604914): avc: denied { read } for name="cache" dev="dm-0" ino=17 scontext=u:r:untrusted_app:s0:c239,c256,c512,c768 tcontext=u:object_r:cache_file:s0 tclass=lnk_file permissive=0
[com.pastryworld] type=1400 audit(0.0:604916): avc: denied { read } for name="cache" dev="dm-0" ino=17 scontext=u:r:untrusted_app:s0:c239,c256,c512,c768 tcontext=u:object_r:cache_file:s0 tclass=lnk_file permissive=0
[System.out] [okhttp]:check permission begin!
[System] ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
[System.out] [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
[System.out] [okhttp]:check permission begin!
[System] ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
[System.out] [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
[System.out] [socket]:check permission begin!
[System] ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
[System.out] [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
[System.out] [socket]:check permission begin!
[System] ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
[System.out] [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
[System.out] [OkHttp] sendRequest<<
[System.out] [OkHttp] sendRequest>>
[System.out] [OkHttp] sendRequest<<
[MagnesPostRequest] MagnesPostRequest returned PayPal-Debug-Id: 28b3d69a7e0ac
[System.out] [okhttp]:check permission begin!
[System] ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
[System.out] [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
[System.out] [socket]:check permission begin!
[System] ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
[System.out] [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
[Surface] Surface::disconnect(this=0x71d20db000,api=1)
[Surface] Surface::disconnect(this=0x7206c80000,api=1)
[PhoneWindow] DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@3d4f8f6, this = DecorView@91df91c[MainActivity]
[PhoneWindow] DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@5ca6631, this = DecorView@6982a4a[DropInActivity]
[Surface] Surface::disconnect(this=0x71d2276000,api=1)
[GED] ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 15, oppidx_max 15, oppidx_min 0
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.pastryworld, PID: 5017
[AndroidRuntime] java.lang.RuntimeException: Unable to instantiate service com.braintreepayments.api.internal.AnalyticsIntentService: java.lang.InstantiationException: java.lang.Class<com.braintreepayments.api.internal.AnalyticsIntentService> cannot be instantiated
[AndroidRuntime] 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3968)
[AndroidRuntime] 	at android.app.ActivityThread.access$1600(ActivityThread.java:226)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1900)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:214)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7386)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
[AndroidRuntime] Caused by: java.lang.InstantiationException: java.lang.Class<com.braintreepayments.api.internal.AnalyticsIntentService> cannot be instantiated
[AndroidRuntime] 	at java.lang.Class.newInstance(Native Method)
[AndroidRuntime] 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
[AndroidRuntime] 	at androidx.core.app.CoreComponentFactory.instantiateService(Unknown Source:0)
[AndroidRuntime] 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3963)
[AndroidRuntime] 	... 8 more
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.RuntimeException: Unable to instantiate service com.braintreepayments.api.internal.AnalyticsIntentService: java.lang.InstantiationException: java.lang.Class<com.braintreepayments.api.internal.AnalyticsIntentService> cannot be instantiated ---> Java.Lang.ReflectiveOperationException: java.lang.Class<com.braintreepayments.api.internal.AnalyticsIntentService> cannot be instantiated
[MonoDroid]    --- End of inner exception stack trace ---
[MonoDroid]   --- End of managed Java.Lang.RuntimeException stack trace ---
[MonoDroid] java.lang.RuntimeException: Unable to instantiate service com.braintreepayments.api.internal.AnalyticsIntentService: java.lang.InstantiationException: java.lang.Class<com.braintreepayments.api.internal.AnalyticsIntentService> cannot be instantiated
[MonoDroid] 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3968)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1900)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:214)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:7386)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
[MonoDroid] Caused by: java.lang.InstantiationException: java.lang.Class<com.braintreepayments.api.internal.AnalyticsIntentService> cannot be instantiated
[MonoDroid] 	at java.lang.Class.newInstance(Native Method)
[MonoDroid] 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
[MonoDroid] 	at androidx.core.app.CoreComponentFactory.instantiateService(Unknown Source:0)
[MonoDroid] 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3963)
[MonoDroid] 	... 8 more
[MonoDroid] 
[Process] Sending signal. PID: 5017 SIG: 9

**Comment by samirgcofficial** [comment]
Any help ??

**Comment by tuyen-vuduc** [comment]
Please check the latest version and reopen in case
