### ISSUE TITLE
Cannot update to Lastest Xamarin forms with this package.

### ISSUE THREAD

**Issue by jmbowman1107** [NAXAM/braintree-android-binding#16]
Hi! It seems Microsoft added an upper bound of Xamarin.Google.Android.Material to 1.3.0 in Xamarin.Forms 5.0.2083 (latest as of 09/08/2021).

Because of this I am unable to update the Xamarin.Forms package (and subsequently Xamarin.Essentials) to the latest releases and also use this library. 

Would it be possible to re-release this package with Xamarin.Google.Android.Material  >= 1.3.0 instead fo 1.3.0.1?

**Comment by iane87** [comment]
I have the same issue I cannot add the DropIn. If I try to add an older version it messes the android manifest up. Please fix. Also, if anyone has a way to get the nonce client side in Xamarin I can work around using the DropIn but all the examples I keep seeing either use DropIn or native code.

**Comment by jmbowman1107** [comment]
For a work around, I copied the dlls that this package installs to my local repo, and referenced them directly without the NuGet package.

**Comment by tuyen-vuduc** [comment]
Please check out the latest version and reopen in case
