### ISSUE TITLE
ThreeDSecure classes have no setters on properties

### ISSUE THREAD

**Issue by cvb941** [NAXAM/braintree-android-binding#18]
Hello,

I'm trying to integrate the 3D Secure client into our Xamarin app.

However, after installing the 3D Secure nuget and trying to use the included classes, they don't seem to have the setters generated on their properties, making them unusable. See the attached screenshots below.

![image](https://user-images.githubusercontent.com/2351527/143872837-cb5b350b-1059-4abd-971c-9ba66bbe1590.png)
![image](https://user-images.githubusercontent.com/2351527/143872981-687ff8b1-df1b-4603-a39e-f749805417a7.png)

Would it be possible to fix this? And what about the newest version of the Braintree SDKs, is it possible to generate bindings for them?

**Comment by tuyen-vuduc** [comment]
Please check the latest version then.
