### ISSUE TITLE
Drop - in UI Support

### ISSUE THREAD

**Issue by abdu292** [NAXAM/braintree-android-binding#2]
Does this support Drop in UI? if no is there any way we can achieve this easy with this package?

Thank you for this library, and any help on the above would be greatly appreciated. Thanks!

**Comment by tuyen-vuduc** [comment]
Each binding library only covers its targeting native library. DropIn UI is another library, not a part of this library. Plz follow Xamarin guide to create a binding library.

Cheers.

**Comment by abdu292** [comment]
Sure, Thank you!
