### ISSUE TITLE
Google Pay option does not show up in drop in UI

### ISSUE THREAD

**Issue by Marilynr** [NAXAM/braintree-android-binding#3]
I am using the Naxam.BraintreeDropIn.Droid library in my Xamarin.Android project and Google Pay option does not show up in the pop-up. I am using a client token that refers to an account with that option enabled. I would like to know if this is the way to add Google Pay to drop in, I have followed the Braintree's documentation but I'm not sure what is wrong. Thanks in advance

Here is the code:

```
DropInRequest dropInRequest = new DropInRequest()
       .ClientToken(clientToken);

TransactionInfo transactionInfo = TransactionInfo.NewBuilder()
                .SetTotalPrice("1.00")
                .SetTotalPriceStatus(WalletConstants.TotalPriceStatusFinal)
                .SetCurrencyCode("USD")
                .Build();

GooglePaymentRequest googlePaymentRequest = new GooglePaymentRequest().InvokeTransactionInfo(transactionInfo);

dropInRequest.InvokeGooglePaymentRequest(googlePaymentRequest);
          
StartActivityForResult(dropInRequest.GetIntent(this), LOAD_PAYMENT_DATA_REQUEST_CODE);

```

- I have Xamarin.GooglePlayServices.Wallet installed(for Google Play Services-Wallet 11.4.2)

- I included the wallet enabled meta-data tag in my AndroidManifest.xml

- I enabled the Google Pay option in my sandbox account

**Comment by tuyen-vuduc** [comment]
Hi,

Sorry for the very late response.

Please check out latest version by simply following DropIn guideline with current sanbox API key in the sample code.

Cheers.
