### ISSUE TITLE
MIssing dependency

### ISSUE THREAD

**Issue by merravid** [NAXAM/braintree-android-binding#5]
It seems there is a missing dependency in the project which means we are unable to build any project using this package with the D8 compiler.

R8 : warning : Missing class: com.kount.api.DataCollector$CompletionHandler

Tried adding this to the -nowarn list in proguard.cfg, but that didn't help.

**Comment by jenishpi** [comment]
I am facing same issues in Xamarin.andorid project. @merravid , Did you find any fix for this?

**Comment by merravid** [comment]
@jenishpi Unfortunately not, we had to fall back to the dx compiler.

**Comment by tuyen-vuduc** [comment]
Would you might checking out latest binding?

**Comment by tuyen-vuduc** [comment]
Hi,

Could you guys share the error in your app?

Thanks.

**Comment by merravid** [comment]
Hi,

Your latest bindings require AndroidX which we do not yet support, so unfortunately we can't test this.

Thanks.
