### ISSUE TITLE
Integration whith a Xamarin Forms

### ISSUE THREAD

**Issue by eolverabea** [NAXAM/braintree-android-binding#6]
Hi, I'm trying to implement Paypal payments in Xamarin Forms, I'm following this implementation guide: http://www.xamboy.com/2020/02/28/braintree-integration-in-xamarin-forms-part-3/
I have generated the token with the briantree PHP library, when I send the token to initialize it sends me the following error:
** Com.Braintreepayments.Api.Exceptions.InvalidArgumentException: ** 'Activity is null'
  public async Task <bool> InitializeAsync (string clientToken)
         {
             try
             {
                
                 initializeTcs = new TaskCompletionSource <bool> ();
                 mBraintreeFragment = BraintreeFragment.NewInstance (CrossCurrentActivity.Current.Activity, clientToken);
              
             
             }
             catch (InvalidArgumentException e)
             {
                 initializeTcs.TrySetException (e);
             }
             return await initializeTcs.Task;
         }

**Comment by tuyen-vuduc** [comment]
Plz set up `CrossCurrentActivity` correctly or you could use Xamarin.Essentials similar function.
