### ISSUE TITLE
Help mapping old 2.x version to current

### ISSUE THREAD

**Issue by csmac3144** [NAXAM/braintree-android-binding#7]
Thanks for all your work on this! Very much appreciated.

The only Xamarin Forms guide I can find is the Rendy article: https://www.xamboy.com/2020/01/28/braintree-integration-in-xamarin-forms-part-1/

I can get his code to build using the old Naxam packages he used. When I update these to the current equivalents (at least I think they are the equivalents) a lot seems to have changed. I tried adding the packages from the sample code in this project (also could not get those samples to build).

Error	CS0117	'Card' does not contain a definition for 'Tokenize'	
Error	CS0117	'GooglePayment' does not contain a definition for 'IsReadyToPay'	
Error	CS0117	'GooglePayment' does not contain a definition for 'RequestPayment'	
Error	CS1061	'GooglePaymentRequest' does not contain a definition for 'InvokeTransactionInfo' 
Error	CS1061	'GooglePaymentRequest' does not contain a definition for 'InvokeTransactionInfo' 
Error	CS0117	'PayPal' does not contain a definition for 'AuthorizeAccount'	
Error	CS0103	The name 'BraintreeFragment' does not exist in the current context	
Error	CS0246	The type or namespace name 'BraintreeFragment' could not be found 

Should I just use the old packages? Is there a straightforward way to understand how these packages have evolved so that maybe I could update the Rendy code?

Thanks again!

**Comment by tuyen-vuduc** [comment]
Hi,

Thanks for reporting the issue.

It would be great if you provide a sample code to check out quickly.

Cheers.

**Comment by csmac3144** [comment]
Thanks tuyen-vuduc!

I'm trying to get just the Drop In UI working in Xamarin Forms for now.

Here is the original Xamarin Forms sample project from Rendy's site:
https://github.com/CrossGeeks/BraintreeXFSample/tree/DropInUI

Here is my attempt so far to get it to work with the new Naxam packages:
https://github.com/csmac3144/Braintree.Tester

In particular, I don't see any way to get these lines to work. There doesn't seem to be anything equivalent to "InvokeTransactionInfo" in the new Naxam bindings...

                GooglePaymentRequest googlePaymentRequest = new GooglePaymentRequest();
                
                googlePaymentRequest.InvokeTransactionInfo(TransactionInfo.NewBuilder()
                                                           .SetTotalPrice($"{totalPrice}")
                .SetTotalPriceStatus(WalletConstants.TotalPriceStatusFinal)
                .SetCurrencyCode("USD")
                .Build());

If I can get all this working with Xamarin Forms I'll publish an update to Rendy's article to assist others.

**Comment by tuyen-vuduc** [comment]
@csmac3144 Plz check out the latest package then. There was an issue with the previous package.

Cheers.

**Comment by winsonet** [comment]
I also have same issue with the latest Braintree Android Binding version, I can't find the reference object for ```BraintreeFragment``` , (error as:  ``` Error CS0246: The type or namespace name 'BraintreeFragment' could not be found (are you missing a using directive or an assembly reference?) ```) and there are no any methods for the ```GooglePayment```, I suppose there is a ```IsReadyToPay``` for it as below:

```GooglePayment.IsReadyToPay(mBraintreeFragment, this);```

thanks!

**Comment by dawitalemu** [comment]
This still remains to be an issue even with the latest nuget releases.

The type or namespace name 'Tokenize' does not exist in the namespace 'Card' (are you missing an assembly reference?)	
The type or namespace name 'BraintreeFragment' could not be found (are you missing a using directive or an assembly reference?)	
The name 'BraintreeFragment' does not exist in the current context	
'GooglePayment' does not contain a definition for 'IsReadyToPay'

It would help a lot if you could just give a definitive guide on how to use your wrappers and what other dependencies it has. Thanks for all the great work you do.

**Comment by tuyen-vuduc** [comment]
@dawitalemu Sorry for the late response. The latest version is just rolled out for DropIn v5.2.0.

Please check it out.
